# Generated by Django 5.1 on 2024-10-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
